namespace RetroBat.Api.Infrastructure;

/// <summary>
/// Ce que la borne affiche au joueur pendant un challenge.
///
/// La langue se resout par couches, et l'ordre compte :
///
///   1. le joueur, quand il est identifie - sa session porte sa langue ;
///   2. la borne, sinon - c'est la langue de la salle, celle qu'un passant
///      comprend le mieux avant de s'etre connecte ;
///   3. l'anglais en dernier recours.
///
/// La borne elle-meme ne change pas de langue quand un joueur arrive :
/// basculer EmulationStation a chaque check-in serait lourd et lent. Seules
/// ces chaines suivent le joueur.
/// </summary>
public static class CabinetAnnounceText
{
    /// <summary>Les langues servies. Toute autre valeur retombe sur l'anglais.</summary>
    private static readonly string[] Supported = ["en", "fr", "es", "ja", "zh", "ko"];

    /// <summary>
    /// Ramene un code quelconque - « fr », « fr_FR », « fr-FR », « FRANCAIS » -
    /// a l'une des six langues servies.
    /// </summary>
    public static string Normalize(string? value)
    {
        var code = (value ?? string.Empty).Trim().ToLowerInvariant();
        if (code.Length == 0)
        {
            return string.Empty;
        }

        // « fr_FR » et « fr-FR » comptent comme « fr ».
        var cut = code.IndexOfAny(['_', '-']);
        if (cut > 0)
        {
            code = code[..cut];
        }

        return Array.IndexOf(Supported, code) >= 0 ? code : string.Empty;
    }

    /// <summary>
    /// La langue a employer, du joueur vers la borne vers l'anglais. Le premier
    /// niveau reconnu gagne : un joueur japonais sur une borne francaise lit du
    /// japonais, un passant anonyme lit du francais.
    /// </summary>
    public static string Resolve(string? playerLocale, string? cabinetLocale)
    {
        var player = Normalize(playerLocale);
        if (player.Length > 0)
        {
            return player;
        }

        var cabinet = Normalize(cabinetLocale);
        return cabinet.Length > 0 ? cabinet : "en";
    }

    /// <summary>La chaine si la table la connait (dans cette langue ou en anglais), sinon null.</summary>
    public static string? Find(string key, string locale)
    {
        var texte = Get(key, locale);
        return string.Equals(texte, key, StringComparison.Ordinal) ? null : texte;
    }

    /// <summary>Une chaine d'annonce dans la langue resolue.</summary>
    public static string Get(string key, string locale)
    {
        var code = Normalize(locale);
        if (code.Length == 0)
        {
            code = "en";
        }

        if (Words.TryGetValue(code, out var table) && table.TryGetValue(key, out var text))
        {
            return text;
        }

        // Repli cle par cle : une chaine ajoutee au francais et pas encore
        // traduite s'affiche en anglais plutot que de disparaitre.
        return Words["en"].TryGetValue(key, out var fallback) ? fallback : key;
    }

    private static readonly Dictionary<string, Dictionary<string, string>> Words = new()
    {
        ["fr"] = new()
        {
            ["start_title"] = "Appuyez sur START pour commencer la partie",
            ["start_sub"] = "Elle sera mise en pause automatiquement - prête pour le départ",
            ["hold_title"] = "Ne touchez plus à rien !",
            ["hold_sub"] = "Partie en pause - départ imminent, attendez le décompte",
            ["reached_title"] = "🏁 Objectif atteint !",
            ["reached_sub"] = "Votre temps est enregistré - regardez le classement !",
            ["end_title"] = "🏁 Challenge terminé !",
            ["end_sub"] = "Classement sur l'écran de la salle - merci d'avoir joué !",
            ["countdown"] = "Départ dans…",
            ["go"] = "GO !",
            ["ready"] = "Tenez-vous prêt !",
            ["launching"] = "Le jeu se lance…",
            ["scan"] = "📱 Scannez pour participer - vos scores à votre nom",
            ["open_to_all"] = "Ouvert à tous",
            ["scoring_certifiable"] = "Partie certifiable",
            ["scoring_for_ranking"] = "pour le classement",
            ["scoring_forced"] = "réglages certifiés appliqués",
            ["scoring_factory_reset"] = "réglages du jeu remis d'usine : {0}",
            ["scoring_not_certifiable"] = "Partie non certifiable",
            ["scoring_frontend_off"] = "{0}, à désactiver dans les options RetroBat de ce jeu",
            ["scoring_danger_rewind"] = "rembobinage (Rewind)",
            ["scoring_danger_runahead"] = "run-ahead",
            ["scoring_danger_autosave"] = "sauvegarde d'état automatique",
            ["scoring_emulator_pending"] = "Émulateur pas encore reconnu",
            ["scoring_emulator_pending_sub"] = "ton score sera gardé et classé dès qu'il le sera",
            ["scoring_settings_pending"] = "Réglages en attente",
            ["scoring_settings_pending_sub"] = "ton score sera gardé et classé dès qu'ils seront reconnus",
            ["scoring_nothing_measured"] = "Aucun score ne sera mesuré",
            ["scoring_module_missing"] = "le module de mesure est absent de cette borne",
            ["scoring_module_idle"] = "le module de mesure n'enveloppe aucun émulateur",
            ["scoring_core_blind"] = "le cœur « {0} » n'expose pas sa mémoire",
            ["scoring_none_measured"] = "Aucun score n'a été mesuré",
            ["scoring_none_measured_sub"] = "la partie annoncée certifiable n'a rien remonté",
            ["scoring_kept_offline"] = "Score {0} gardé sur la borne : il partira au retour de NelfePlay",
            ["scoring_deferred_sent"] = "NelfePlay est de retour : {0} partie(s) gardée(s) sur la borne envoyée(s)",
            ["scoring_deferred_sent_rank"] = "NelfePlay est de retour : {0} partie(s) envoyée(s), meilleur rang #{1}",
            ["scoring_offline"] = "NelfePlay injoignable",
            ["scoring_offline_sub"] = "joue normalement : ton score partira dès son retour",
            ["scoring_offline_certifiable_sub"] = "partie certifiable : ton score partira au retour de NelfePlay",
            ["reason_profile_content_mismatch"] = "ROM non reconnue",
            ["reason_profile_mem_mismatch"] = "définition mémoire non reconnue",
            ["reason_game_mode_unmeasured"] = "mode de jeu non mesuré : mets APIExpose à jour",
            ["reason_profile_api_outdated"] = "version d'APIExpose trop ancienne pour ce classement : mets APIExpose à jour",
            ["reason_game_mode_mismatch"] = "mode de jeu différent de ce classement",
            ["reason_game_difficulty_unmeasured"] = "difficulté non mesurée",
            ["reason_game_difficulty_not_allowed"] = "difficulté non autorisée pour ce classement",
            ["reason_game_multiplayer"] = "partie à plusieurs : pas de classement solo",
            ["reason_profile_listener_unauthorized"] = "listener non homologué (wrapper ou plugin MAME)",
            ["reason_profile_not_open"] = "classement fermé",
            ["reason_profile_nvram_mismatch"] = "réglages internes du jeu différents de ceux d'usine",
            ["reason_profile_bios_mismatch"] = "BIOS non reconnu",
            ["reason_profile_mismatch"] = "jeu ou règlement non concordant",
            ["reason_runtime_module_unauthorized"] = "logiciel non homologué",
            ["replay_uncertain"] = "Lecture incertaine",
            ["replay_downloading"] = "Téléchargement du replay…",
            ["replay_download_percent"] = "Téléchargement {0} %",
            ["replay_download_eta"] = "encore {0} s",
            ["replay_download_size"] = "{0} Mo sur {1}",
            ["replay_this_core"] = "ce cœur",
            ["replay_core_other"] = "Ce record a été enregistré avec une autre version de {0}. La lecture peut s'interrompre avant la fin.",
            ["replay_core_other_local"] = "Ce record a été enregistré avec une autre version de {0} : cette borne a la {1}. La lecture peut s'interrompre avant la fin.",
            ["replay_rom_other"] = "Cette borne n'a pas le fichier exact sur lequel ce record a été joué : la lecture part sur {0}. Si le jeu diffère (région, révision), le replay peut dériver.",
            ["replay_rom_other_crc"] = "Cette borne n'a pas le fichier exact sur lequel ce record a été joué (empreinte {1}) : la lecture part sur {0}. Si le jeu diffère (région, révision), le replay peut dériver.",
            ["scoring_continue_title"] = "Continue : ton score certifié reste {0}",
            ["scoring_continue_sub"] = "la partie continue, mais la suite ne compte plus pour le classement",
            ["scoring_credit_title"] = "Crédit consommé : ton score certifié reste {0}",
            ["scoring_credit_sub"] = "la partie qui vient n'est pas certifiable : quitte et relance le jeu pour une partie certifiée",
            ["scoring_uncertified_title"] = "Partie non certifiable",
            ["scoring_credits_muted_title"] = "Crédits illisibles : partie non certifiable",
            ["scoring_credits_muted_sub"] = "pièces trop rapides ; pour une partie certifiée, quitte et relance le jeu",
            ["scoring_uncertified_sub"] = "pour une partie certifiée, quitte et relance le jeu",
            ["scoring_multiplayer_title"] = "Partie à plusieurs : hors classement solo",
            ["scoring_multiplayer_sub"] = "l'arrivée d'un joueur ne compte pas comme un continue",
            ["scoring_joined_title"] = "Un joueur te rejoint : ton score solo certifié reste {0}",
            ["scoring_joined_sub"] = "la suite se joue à plusieurs, hors classement solo",
            ["netplay_player_title"] = "Tu rejoins {0} en JOUEUR",
            ["netplay_player_sub"] = "ta manette pilote ta place dans sa partie",
            ["netplay_spectator_title"] = "Tu regardes {0} en SPECTATEUR",
            ["netplay_spectator_sub"] = "tes boutons envoient des réactions",
            ["netplay_this_live"] = "ce direct",
            ["netplay_host_left_title"] = "{0} a quitté la partie",
            ["netplay_host_left_sub"] = "la partie en ligne est finie, le jeu se ferme",
            ["netplay_the_host"] = "L'hôte",
            ["replay_searching"] = "Recherche du replay…",
            ["replay_searching_sub"] = "auprès des bornes qui le gardent",
            ["replay_1lc_end"] = "Fin du 1LC",
            ["replay_1lc_end_sub"] = "Première vie perdue : le score du 1LC s'arrête ici.",
            ["replay_no_seek"] = "Pas d'avance rapide",
            ["replay_no_seek_sub"] = "Ce replay a été enregistré sans points de contrôle : il se regarde d'un bout à l'autre.",
            ["world_scoring_updated"] = "World Scoring à jour : {0} jeux prêts sur cette borne",
            ["world_scoring_updated_one"] = "World Scoring à jour : {0} jeu prêt sur cette borne",
            ["replay_requested"] = "Replay pas encore disponible",
            ["replay_requested_sub"] = "demandé à la borne qui l'a enregistré : réessaie dans quelques minutes",
            ["replay_unavailable"] = "Replay introuvable pour l'instant",
            ["replay_unavailable_sub"] = "aucune borne en ligne ne le partage",
            ["replay_rom_missing"] = "Jeu absent de cette borne",
            ["replay_rom_missing_sub"] = "il faut le jeu sur cette borne pour lire ce replay",
            ["replay_core_missing"] = "Émulateur absent de cette borne",
            ["replay_core_missing_sub"] = "il faut l'émulateur du record pour lire ce replay",
        },
        ["en"] = new()
        {
            ["start_title"] = "Press START to begin",
            ["start_sub"] = "It will pause on its own - ready for the countdown",
            ["hold_title"] = "Hands off!",
            ["hold_sub"] = "Paused - the start is close, wait for the countdown",
            ["reached_title"] = "🏁 Target reached!",
            ["reached_sub"] = "Your time is recorded - watch the leaderboard!",
            ["end_title"] = "🏁 Challenge over!",
            ["end_sub"] = "Leaderboard on the venue screen - thanks for playing!",
            ["countdown"] = "Starting in…",
            ["go"] = "GO!",
            ["ready"] = "Get ready!",
            ["launching"] = "Launching the game…",
            ["scan"] = "📱 Scan to join - your scores under your name",
            ["open_to_all"] = "Open to all",
            ["scoring_certifiable"] = "Certifiable run",
            ["scoring_for_ranking"] = "for the leaderboard",
            ["scoring_forced"] = "certified settings applied",
            ["scoring_factory_reset"] = "game settings reset to factory: {0}",
            ["scoring_not_certifiable"] = "Run not certifiable",
            ["scoring_frontend_off"] = "{0}: turn it off in this game's RetroBat options",
            ["scoring_danger_rewind"] = "rewind",
            ["scoring_danger_runahead"] = "run-ahead",
            ["scoring_danger_autosave"] = "automatic save state",
            ["scoring_emulator_pending"] = "Emulator not recognized yet",
            ["scoring_emulator_pending_sub"] = "your score will be kept and ranked as soon as it is",
            ["scoring_settings_pending"] = "Settings pending",
            ["scoring_settings_pending_sub"] = "your score will be kept and ranked as soon as they are recognized",
            ["scoring_nothing_measured"] = "No score will be measured",
            ["scoring_module_missing"] = "the measurement module is missing on this cabinet",
            ["scoring_module_idle"] = "the measurement module wraps no emulator",
            ["scoring_core_blind"] = "the “{0}” core does not expose its memory",
            ["scoring_none_measured"] = "No score was measured",
            ["scoring_none_measured_sub"] = "the run announced as certifiable reported nothing",
            ["scoring_kept_offline"] = "Score {0} kept on this cabinet: it will be sent when NelfePlay is back",
            ["scoring_deferred_sent"] = "NelfePlay is back: {0} game(s) kept on this cabinet were sent",
            ["scoring_deferred_sent_rank"] = "NelfePlay is back: {0} game(s) sent, best rank #{1}",
            ["scoring_offline"] = "NelfePlay unreachable",
            ["scoring_offline_sub"] = "play as usual: your score will be sent when it is back",
            ["scoring_offline_certifiable_sub"] = "certifiable run: your score will be sent when NelfePlay is back",
            ["reason_profile_content_mismatch"] = "ROM not recognized",
            ["reason_profile_mem_mismatch"] = "memory definition not recognized",
            ["reason_game_mode_unmeasured"] = "game mode not measured: update APIExpose",
            ["reason_profile_api_outdated"] = "APIExpose version too old for this ranking: update APIExpose",
            ["reason_game_mode_mismatch"] = "game mode differs from this leaderboard",
            ["reason_game_difficulty_unmeasured"] = "difficulty not measured",
            ["reason_game_difficulty_not_allowed"] = "difficulty not allowed on this leaderboard",
            ["reason_game_multiplayer"] = "multiplayer game: not ranked solo",
            ["reason_profile_listener_unauthorized"] = "measurement module not approved (wrapper or MAME plugin)",
            ["reason_profile_not_open"] = "leaderboard closed",
            ["reason_profile_nvram_mismatch"] = "the game's internal settings differ from factory settings",
            ["reason_profile_bios_mismatch"] = "BIOS not recognized",
            ["reason_profile_mismatch"] = "game or ruleset mismatch",
            ["reason_runtime_module_unauthorized"] = "unapproved software",
            ["replay_uncertain"] = "Uncertain playback",
            ["replay_downloading"] = "Downloading the replay…",
            ["replay_download_percent"] = "Downloading {0}%",
            ["replay_download_eta"] = "{0} s left",
            ["replay_download_size"] = "{0} MB of {1}",
            ["replay_this_core"] = "this core",
            ["replay_core_other"] = "This record was made with another version of {0}. Playback may stop before the end.",
            ["replay_core_other_local"] = "This record was made with another version of {0}: this cabinet has {1}. Playback may stop before the end.",
            ["replay_rom_other"] = "This cabinet does not have the exact file this record was played on: playback uses {0}. If the game differs (region, revision), the replay may drift.",
            ["replay_rom_other_crc"] = "This cabinet does not have the exact file this record was played on (checksum {1}): playback uses {0}. If the game differs (region, revision), the replay may drift.",
            ["scoring_continue_title"] = "Continue: your certified score stays at {0}",
            ["scoring_continue_sub"] = "keep playing, but what follows no longer counts for the ranking",
            ["scoring_credit_title"] = "Credit used: your certified score stays at {0}",
            ["scoring_credit_sub"] = "the game ahead is not certifiable: quit and relaunch it for a certified game",
            ["scoring_uncertified_title"] = "Game not certifiable",
            ["scoring_credits_muted_title"] = "Credits unreadable: game not certifiable",
            ["scoring_credits_muted_sub"] = "coins inserted too fast; for a certified game, quit and relaunch it",
            ["scoring_uncertified_sub"] = "for a certified game, quit and relaunch it",
            ["scoring_multiplayer_title"] = "Multiplayer game: outside the solo ranking",
            ["scoring_multiplayer_sub"] = "a player joining does not count as a continue",
            ["scoring_joined_title"] = "A player joined you: your certified solo score stays at {0}",
            ["scoring_joined_sub"] = "the rest is played together, outside the solo ranking",
            ["netplay_player_title"] = "You join {0} as a PLAYER",
            ["netplay_player_sub"] = "your controller drives your seat in their game",
            ["netplay_spectator_title"] = "You watch {0} as a SPECTATOR",
            ["netplay_spectator_sub"] = "your buttons send reactions",
            ["netplay_this_live"] = "this live",
            ["netplay_host_left_title"] = "{0} left the game",
            ["netplay_host_left_sub"] = "the online game is over, closing the game",
            ["netplay_the_host"] = "The host",
            ["replay_searching"] = "Looking for the replay…",
            ["replay_searching_sub"] = "on the cabinets that keep it",
            ["replay_1lc_end"] = "End of the 1LC",
            ["replay_1lc_end_sub"] = "First life lost: the 1LC score stops here.",
            ["replay_no_seek"] = "No fast-forward",
            ["replay_no_seek_sub"] = "This replay was recorded without checkpoints: it plays from start to finish.",
            ["world_scoring_updated"] = "World Scoring updated: {0} games ready on this cabinet",
            ["world_scoring_updated_one"] = "World Scoring updated: {0} game ready on this cabinet",
            ["replay_requested"] = "Replay not available yet",
            ["replay_requested_sub"] = "requested from the cabinet that recorded it: try again in a few minutes",
            ["replay_unavailable"] = "Replay can't be found right now",
            ["replay_unavailable_sub"] = "no cabinet online is sharing it",
            ["replay_rom_missing"] = "Game missing on this cabinet",
            ["replay_rom_missing_sub"] = "this cabinet needs the game to play this replay",
            ["replay_core_missing"] = "Emulator missing on this cabinet",
            ["replay_core_missing_sub"] = "this replay needs the record's emulator",
        },
        ["es"] = new()
        {
            ["start_title"] = "Pulsa START para empezar la partida",
            ["start_sub"] = "Se pausará sola - lista para la salida",
            ["hold_title"] = "¡No toques nada!",
            ["hold_sub"] = "En pausa - la salida es inminente, espera la cuenta atrás",
            ["reached_title"] = "🏁 ¡Objetivo alcanzado!",
            ["reached_sub"] = "Tu tiempo queda registrado - ¡mira la clasificación!",
            ["end_title"] = "🏁 ¡Reto terminado!",
            ["end_sub"] = "Clasificación en la pantalla de la sala - ¡gracias por jugar!",
            ["countdown"] = "Salida en…",
            ["go"] = "¡YA!",
            ["ready"] = "¡Prepárate!",
            ["launching"] = "Lanzando el juego…",
            ["scan"] = "📱 Escanea para participar - tus puntuaciones a tu nombre",
            ["open_to_all"] = "Abierto a todos",
            ["scoring_certifiable"] = "Partida certificable",
            ["scoring_for_ranking"] = "para la clasificación",
            ["scoring_forced"] = "ajustes certificados aplicados",
            ["scoring_factory_reset"] = "ajustes del juego restablecidos de fábrica: {0}",
            ["scoring_not_certifiable"] = "Partida no certificable",
            ["scoring_frontend_off"] = "{0}: desactívalo en las opciones de RetroBat de este juego",
            ["scoring_danger_rewind"] = "rebobinado (Rewind)",
            ["scoring_danger_runahead"] = "run-ahead",
            ["scoring_danger_autosave"] = "guardado de estado automático",
            ["scoring_emulator_pending"] = "Emulador aún no reconocido",
            ["scoring_emulator_pending_sub"] = "tu puntuación se guardará y se clasificará en cuanto lo sea",
            ["scoring_settings_pending"] = "Ajustes pendientes",
            ["scoring_settings_pending_sub"] = "tu puntuación se guardará y se clasificará en cuanto se reconozcan",
            ["scoring_nothing_measured"] = "No se medirá ninguna puntuación",
            ["scoring_module_missing"] = "falta el módulo de medición en esta máquina",
            ["scoring_module_idle"] = "el módulo de medición no envuelve ningún emulador",
            ["scoring_core_blind"] = "el núcleo «{0}» no expone su memoria",
            ["scoring_none_measured"] = "No se ha medido ninguna puntuación",
            ["scoring_none_measured_sub"] = "la partida anunciada como certificable no ha transmitido nada",
            ["scoring_kept_offline"] = "Puntuación {0} guardada en la máquina: se enviará cuando vuelva NelfePlay",
            ["scoring_deferred_sent"] = "NelfePlay ha vuelto: se han enviado {0} partida(s) guardada(s) en la máquina",
            ["scoring_deferred_sent_rank"] = "NelfePlay ha vuelto: {0} partida(s) enviada(s), mejor puesto #{1}",
            ["scoring_offline"] = "NelfePlay no responde",
            ["scoring_offline_sub"] = "juega con normalidad: tu puntuación se enviará cuando vuelva",
            ["scoring_offline_certifiable_sub"] = "partida certificable: tu puntuación se enviará cuando vuelva NelfePlay",
            ["reason_profile_content_mismatch"] = "ROM no reconocida",
            ["reason_profile_mem_mismatch"] = "definición de memoria no reconocida",
            ["reason_game_mode_unmeasured"] = "modo de juego no medido: actualiza APIExpose",
            ["reason_profile_api_outdated"] = "versión de APIExpose demasiado antigua para esta clasificación: actualiza APIExpose",
            ["reason_game_mode_mismatch"] = "modo de juego distinto de esta clasificación",
            ["reason_game_difficulty_unmeasured"] = "dificultad no medida",
            ["reason_game_difficulty_not_allowed"] = "dificultad no permitida en esta clasificación",
            ["reason_game_multiplayer"] = "partida a varios: sin clasificación individual",
            ["reason_profile_listener_unauthorized"] = "módulo de medición no homologado (wrapper o plugin de MAME)",
            ["reason_profile_not_open"] = "clasificación cerrada",
            ["reason_profile_nvram_mismatch"] = "los ajustes internos del juego difieren de los de fábrica",
            ["reason_profile_bios_mismatch"] = "BIOS no reconocida",
            ["reason_profile_mismatch"] = "juego o reglamento no coincidente",
            ["reason_runtime_module_unauthorized"] = "software no homologado",
            ["replay_uncertain"] = "Reproducción incierta",
            ["replay_downloading"] = "Descargando la repetición…",
            ["replay_download_percent"] = "Descargando {0} %",
            ["replay_download_eta"] = "quedan {0} s",
            ["replay_download_size"] = "{0} MB de {1}",
            ["replay_this_core"] = "este núcleo",
            ["replay_core_other"] = "Este récord se grabó con otra versión de {0}. La reproducción puede detenerse antes del final.",
            ["replay_core_other_local"] = "Este récord se grabó con otra versión de {0}: esta máquina tiene la {1}. La reproducción puede detenerse antes del final.",
            ["replay_rom_other"] = "Esta máquina no tiene el archivo exacto con el que se jugó este récord: la reproducción usa {0}. Si el juego difiere (región, revisión), la repetición puede desviarse.",
            ["replay_rom_other_crc"] = "Esta máquina no tiene el archivo exacto con el que se jugó este récord (huella {1}): la reproducción usa {0}. Si el juego difiere (región, revisión), la repetición puede desviarse.",
            ["scoring_continue_title"] = "Continuación: tu puntuación certificada se queda en {0}",
            ["scoring_continue_sub"] = "la partida sigue, pero lo que venga ya no cuenta para la clasificación",
            ["scoring_credit_title"] = "Crédito consumido: tu puntuación certificada se queda en {0}",
            ["scoring_credit_sub"] = "la partida que viene no es certificable: sal y vuelve a lanzar el juego para una partida certificada",
            ["scoring_uncertified_title"] = "Partida no certificable",
            ["scoring_credits_muted_title"] = "Créditos ilegibles: partida no certificable",
            ["scoring_credits_muted_sub"] = "monedas demasiado rápidas; para una partida certificada, sal y vuelve a lanzar el juego",
            ["scoring_uncertified_sub"] = "para una partida certificada, sal y vuelve a lanzar el juego",
            ["scoring_multiplayer_title"] = "Partida a varios: fuera de la clasificación individual",
            ["scoring_multiplayer_sub"] = "la llegada de un jugador no cuenta como continuación",
            ["scoring_joined_title"] = "Un jugador se ha unido: tu puntuación individual certificada se queda en {0}",
            ["scoring_joined_sub"] = "lo que sigue se juega a varios, fuera de la clasificación individual",
            ["netplay_player_title"] = "Te unes a {0} como JUGADOR",
            ["netplay_player_sub"] = "tu mando controla tu puesto en su partida",
            ["netplay_spectator_title"] = "Miras a {0} como ESPECTADOR",
            ["netplay_spectator_sub"] = "tus botones envían reacciones",
            ["netplay_this_live"] = "este directo",
            ["netplay_host_left_title"] = "{0} ha salido de la partida",
            ["netplay_host_left_sub"] = "la partida en línea ha terminado, el juego se cierra",
            ["netplay_the_host"] = "El anfitrión",
            ["replay_searching"] = "Buscando la repetición…",
            ["replay_searching_sub"] = "en las máquinas que la guardan",
            ["replay_1lc_end"] = "Fin del 1LC",
            ["replay_1lc_end_sub"] = "Primera vida perdida: la puntuación del 1LC termina aquí.",
            ["replay_no_seek"] = "Sin avance rápido",
            ["replay_no_seek_sub"] = "Esta repetición se grabó sin puntos de control: se ve de principio a fin.",
            ["world_scoring_updated"] = "World Scoring actualizado: {0} juegos listos en esta máquina",
            ["world_scoring_updated_one"] = "World Scoring actualizado: {0} juego listo en esta máquina",
            ["replay_requested"] = "Repetición aún no disponible",
            ["replay_requested_sub"] = "pedida a la máquina que la grabó: vuelve a intentarlo en unos minutos",
            ["replay_unavailable"] = "Repetición no encontrada por ahora",
            ["replay_unavailable_sub"] = "ninguna máquina en línea la comparte",
            ["replay_rom_missing"] = "Juego ausente en esta máquina",
            ["replay_rom_missing_sub"] = "esta máquina necesita el juego para ver esta repetición",
            ["replay_core_missing"] = "Emulador ausente en esta máquina",
            ["replay_core_missing_sub"] = "esta repetición necesita el emulador del récord",
        },
        ["ja"] = new()
        {
            ["start_title"] = "START を押してプレイ開始",
            ["start_sub"] = "自動で一時停止します - スタートの準備へ",
            ["hold_title"] = "そのままお待ちください",
            ["hold_sub"] = "一時停止中 - まもなくスタート、カウントをお待ちください",
            ["reached_title"] = "🏁 目標達成！",
            ["reached_sub"] = "タイムを記録しました - ランキングをご覧ください",
            ["end_title"] = "🏁 チャレンジ終了！",
            ["end_sub"] = "順位は会場の画面に - ご参加ありがとうございました",
            ["countdown"] = "スタートまで…",
            ["go"] = "GO！",
            ["ready"] = "ご準備ください",
            ["launching"] = "ゲームを起動しています…",
            ["scan"] = "📱 スキャンして参加 - スコアはあなたの名前で",
            ["open_to_all"] = "どなたでも参加できます",
            ["scoring_certifiable"] = "認定対象のプレイ",
            ["scoring_for_ranking"] = "ランキングに反映されます",
            ["scoring_forced"] = "認定設定を適用しました",
            ["scoring_factory_reset"] = "ゲーム設定を工場出荷時に戻しました：{0}",
            ["scoring_not_certifiable"] = "認定対象外のプレイ",
            ["scoring_frontend_off"] = "{0}：このゲームの RetroBat オプションで無効にしてください",
            ["scoring_danger_rewind"] = "巻き戻し（Rewind）",
            ["scoring_danger_runahead"] = "ランアヘッド",
            ["scoring_danger_autosave"] = "自動ステートセーブ",
            ["scoring_emulator_pending"] = "エミュレーターは未認識です",
            ["scoring_emulator_pending_sub"] = "認識され次第、スコアは保存されランキングに反映されます",
            ["scoring_settings_pending"] = "設定の確認待ち",
            ["scoring_settings_pending_sub"] = "設定が認識され次第、スコアは保存されランキングに反映されます",
            ["scoring_nothing_measured"] = "スコアは計測されません",
            ["scoring_module_missing"] = "この筐体には計測モジュールがありません",
            ["scoring_module_idle"] = "計測モジュールがどのエミュレーターにも適用されていません",
            ["scoring_core_blind"] = "コア「{0}」はメモリを公開していません",
            ["scoring_none_measured"] = "スコアは計測されませんでした",
            ["scoring_none_measured_sub"] = "認定対象と表示されたプレイから何も届きませんでした",
            ["scoring_kept_offline"] = "スコア {0} を筐体に保存しました。NelfePlay の復旧後に送信されます",
            ["scoring_deferred_sent"] = "NelfePlay が復旧しました。筐体に保存していた {0} 件のプレイを送信しました",
            ["scoring_deferred_sent_rank"] = "NelfePlay が復旧しました。{0} 件を送信、最高順位 #{1}",
            ["scoring_offline"] = "NelfePlay に接続できません",
            ["scoring_offline_sub"] = "そのままプレイしてください。復旧後にスコアが送信されます",
            ["scoring_offline_certifiable_sub"] = "認定対象のプレイです。NelfePlay の復旧後にスコアが送信されます",
            ["reason_profile_content_mismatch"] = "ROM が認識されません",
            ["reason_profile_mem_mismatch"] = "メモリ定義が認識されません",
            ["reason_game_mode_unmeasured"] = "ゲームモードを計測できません：APIExposeを更新してください",
            ["reason_profile_api_outdated"] = "このランキングにはAPIExposeのバージョンが古すぎます：APIExposeを更新してください",
            ["reason_game_mode_mismatch"] = "ゲームモードがこのランキングと異なります",
            ["reason_game_difficulty_unmeasured"] = "難易度を計測できません",
            ["reason_game_difficulty_not_allowed"] = "このランキングでは許可されていない難易度です",
            ["reason_game_multiplayer"] = "複数人プレイ：ソロランキング対象外",
            ["reason_profile_listener_unauthorized"] = "計測モジュールが未承認です（wrapper または MAME プラグイン）",
            ["reason_profile_not_open"] = "ランキングは終了しています",
            ["reason_profile_nvram_mismatch"] = "ゲーム内部の設定が工場出荷時と異なります",
            ["reason_profile_bios_mismatch"] = "BIOS が認識されません",
            ["reason_profile_mismatch"] = "ゲームまたはルールが一致しません",
            ["reason_runtime_module_unauthorized"] = "未承認のソフトウェア",
            ["replay_uncertain"] = "再生が不安定になる可能性",
            ["replay_downloading"] = "リプレイをダウンロード中…",
            ["replay_download_percent"] = "ダウンロード中 {0}%",
            ["replay_download_eta"] = "残り {0} 秒",
            ["replay_download_size"] = "{0} MB / {1}",
            ["replay_this_core"] = "このコア",
            ["replay_core_other"] = "この記録は別のバージョンの {0} で作成されました。最後まで再生できない場合があります。",
            ["replay_core_other_local"] = "この記録は別のバージョンの {0} で作成されました（この筐体は {1}）。最後まで再生できない場合があります。",
            ["replay_rom_other"] = "この筐体には記録時と同じファイルがありません。{0} で再生します。ゲームが異なる場合（地域、リビジョン）、リプレイがずれることがあります。",
            ["replay_rom_other_crc"] = "この筐体には記録時と同じファイル（チェックサム {1}）がありません。{0} で再生します。ゲームが異なる場合（地域、リビジョン）、リプレイがずれることがあります。",
            ["scoring_continue_title"] = "コンティニュー：認定スコアは {0} のまま",
            ["scoring_continue_sub"] = "プレイは続けられますが、この先はランキングに数えられません",
            ["scoring_credit_title"] = "クレジット使用：認定スコアは {0} のまま",
            ["scoring_credit_sub"] = "この先のプレイは認定対象外です。認定プレイにはゲームを終了して再起動してください",
            ["scoring_uncertified_title"] = "認定対象外のプレイ",
            ["scoring_credits_muted_title"] = "クレジットを読み取れません：認定対象外のプレイ",
            ["scoring_credits_muted_sub"] = "コインの投入が速すぎます。認定プレイにはゲームを終了して再起動してください",
            ["scoring_uncertified_sub"] = "認定プレイにはゲームを終了して再起動してください",
            ["scoring_multiplayer_title"] = "複数人プレイ：ソロランキング対象外",
            ["scoring_multiplayer_sub"] = "プレイヤーの参加はコンティニューとして扱われません",
            ["scoring_joined_title"] = "プレイヤーが参加：ソロの認定スコアは {0} のまま",
            ["scoring_joined_sub"] = "この先は複数人プレイとなり、ソロランキングの対象外です",
            ["netplay_player_title"] = "{0} のゲームに プレイヤー として参加",
            ["netplay_player_sub"] = "コントローラーで自分の席を操作します",
            ["netplay_spectator_title"] = "{0} のゲームを 観戦 中",
            ["netplay_spectator_sub"] = "ボタンでリアクションを送れます",
            ["netplay_this_live"] = "このライブ",
            ["netplay_host_left_title"] = "{0} がゲームを終了しました",
            ["netplay_host_left_sub"] = "オンライン対戦は終了しました。ゲームを閉じます",
            ["netplay_the_host"] = "ホスト",
            ["replay_searching"] = "リプレイを探しています…",
            ["replay_searching_sub"] = "保存している筐体に問い合わせ中",
            ["replay_1lc_end"] = "1LCの終了",
            ["replay_1lc_end_sub"] = "最初のライフを失いました。1LCのスコアはここまでです。",
            ["replay_no_seek"] = "早送りできません",
            ["replay_no_seek_sub"] = "このリプレイはチェックポイントなしで記録されたため、最初から最後まで再生されます。",
            ["world_scoring_updated"] = "World Scoring を更新しました：この筐体で {0} 本のゲームが遊べます",
            ["world_scoring_updated_one"] = "World Scoring を更新しました：この筐体で {0} 本のゲームが遊べます",
            ["replay_requested"] = "リプレイはまだ利用できません",
            ["replay_requested_sub"] = "録画した筐体に依頼しました。数分後にもう一度お試しください",
            ["replay_unavailable"] = "現在リプレイが見つかりません",
            ["replay_unavailable_sub"] = "共有しているオンラインの筐体がありません",
            ["replay_rom_missing"] = "この筐体にゲームがありません",
            ["replay_rom_missing_sub"] = "このリプレイの再生にはゲームが必要です",
            ["replay_core_missing"] = "この筐体にエミュレーターがありません",
            ["replay_core_missing_sub"] = "このリプレイには記録時のエミュレーターが必要です",
        },
        ["zh"] = new()
        {
            ["start_title"] = "按 START 开始游戏",
            ["start_sub"] = "它会自动暂停 - 等待发车",
            ["hold_title"] = "请勿操作！",
            ["hold_sub"] = "已暂停 - 马上开始，请等待倒数",
            ["reached_title"] = "🏁 达成目标！",
            ["reached_sub"] = "你的成绩已记录 - 看看排行榜！",
            ["end_title"] = "🏁 挑战结束！",
            ["end_sub"] = "排名显示在场馆屏幕上 - 感谢参与！",
            ["countdown"] = "倒数…",
            ["go"] = "GO！",
            ["ready"] = "请准备！",
            ["launching"] = "正在启动游戏…",
            ["scan"] = "📱 扫码参与 - 成绩记在你的名下",
            ["open_to_all"] = "所有人皆可参加",
            ["scoring_certifiable"] = "可认证的对局",
            ["scoring_for_ranking"] = "计入排行榜",
            ["scoring_forced"] = "已应用认证设置",
            ["scoring_factory_reset"] = "游戏设置已恢复出厂值：{0}",
            ["scoring_not_certifiable"] = "不可认证的对局",
            ["scoring_frontend_off"] = "{0}：请在此游戏的 RetroBat 选项中关闭",
            ["scoring_danger_rewind"] = "倒带（Rewind）",
            ["scoring_danger_runahead"] = "预运行（run-ahead）",
            ["scoring_danger_autosave"] = "自动即时存档",
            ["scoring_emulator_pending"] = "模拟器尚未被识别",
            ["scoring_emulator_pending_sub"] = "识别后，你的分数将被保留并计入排行榜",
            ["scoring_settings_pending"] = "设置待确认",
            ["scoring_settings_pending_sub"] = "设置被识别后，你的分数将被保留并计入排行榜",
            ["scoring_nothing_measured"] = "不会测量任何分数",
            ["scoring_module_missing"] = "此机台缺少测量模块",
            ["scoring_module_idle"] = "测量模块未挂接任何模拟器",
            ["scoring_core_blind"] = "核心“{0}”不公开其内存",
            ["scoring_none_measured"] = "未测量到任何分数",
            ["scoring_none_measured_sub"] = "被标记为可认证的对局没有上报任何数据",
            ["scoring_kept_offline"] = "分数 {0} 已保存在本机：NelfePlay 恢复后将自动发送",
            ["scoring_deferred_sent"] = "NelfePlay 已恢复：本机保存的 {0} 局已发送",
            ["scoring_deferred_sent_rank"] = "NelfePlay 已恢复：已发送 {0} 局，最佳排名 #{1}",
            ["scoring_offline"] = "无法连接 NelfePlay",
            ["scoring_offline_sub"] = "请照常游戏：恢复后将发送你的分数",
            ["scoring_offline_certifiable_sub"] = "可认证对局：NelfePlay 恢复后将发送你的分数",
            ["reason_profile_content_mismatch"] = "ROM 未被识别",
            ["reason_profile_mem_mismatch"] = "内存定义未被识别",
            ["reason_game_mode_unmeasured"] = "未测得游戏模式：请更新 APIExpose",
            ["reason_profile_api_outdated"] = "APIExpose 版本过旧，无法参加此排行榜：请更新 APIExpose",
            ["reason_game_mode_mismatch"] = "游戏模式与此排行榜不符",
            ["reason_game_difficulty_unmeasured"] = "未测得难度",
            ["reason_game_difficulty_not_allowed"] = "此排行榜不允许该难度",
            ["reason_game_multiplayer"] = "多人游戏：不计入单人排行",
            ["reason_profile_listener_unauthorized"] = "测量模块未经认可（wrapper 或 MAME 插件）",
            ["reason_profile_not_open"] = "排行榜已关闭",
            ["reason_profile_nvram_mismatch"] = "游戏内部设置与出厂设置不同",
            ["reason_profile_bios_mismatch"] = "BIOS 未被识别",
            ["reason_profile_mismatch"] = "游戏或规则不一致",
            ["reason_runtime_module_unauthorized"] = "未经认可的软件",
            ["replay_uncertain"] = "回放可能不稳定",
            ["replay_downloading"] = "正在下载回放…",
            ["replay_download_percent"] = "正在下载 {0}%",
            ["replay_download_eta"] = "还剩 {0} 秒",
            ["replay_download_size"] = "{0} MB / {1}",
            ["replay_this_core"] = "该核心",
            ["replay_core_other"] = "此记录是用另一个版本的 {0} 录制的。回放可能在结束前中断。",
            ["replay_core_other_local"] = "此记录是用另一个版本的 {0} 录制的：本机为 {1}。回放可能在结束前中断。",
            ["replay_rom_other"] = "本机没有录制此记录时使用的同一文件：将使用 {0} 回放。如果游戏不同（地区、版本），回放可能出现偏差。",
            ["replay_rom_other_crc"] = "本机没有录制此记录时使用的同一文件（校验值 {1}）：将使用 {0} 回放。如果游戏不同（地区、版本），回放可能出现偏差。",
            ["scoring_continue_title"] = "续关：认证分数保持为 {0}",
            ["scoring_continue_sub"] = "游戏继续，但之后的得分不再计入排行榜",
            ["scoring_credit_title"] = "已使用投币：认证分数保持为 {0}",
            ["scoring_credit_sub"] = "接下来的游戏无法认证：如需认证游戏，请退出并重新启动游戏",
            ["scoring_uncertified_title"] = "本局无法认证",
            ["scoring_credits_muted_title"] = "无法读取投币数：本局无法认证",
            ["scoring_credits_muted_sub"] = "投币过快；如需认证游戏，请退出并重新启动游戏",
            ["scoring_uncertified_sub"] = "如需认证游戏，请退出并重新启动游戏",
            ["scoring_multiplayer_title"] = "多人游戏：不计入单人排行",
            ["scoring_multiplayer_sub"] = "玩家加入不算作续关",
            ["scoring_joined_title"] = "有玩家加入：你的单人认证分数保持为 {0}",
            ["scoring_joined_sub"] = "之后为多人游戏，不计入单人排行",
            ["netplay_player_title"] = "你以玩家身份加入 {0}",
            ["netplay_player_sub"] = "你的手柄控制你在对方游戏中的位置",
            ["netplay_spectator_title"] = "你正在观看 {0}",
            ["netplay_spectator_sub"] = "按键可发送反应",
            ["netplay_this_live"] = "这场直播",
            ["netplay_host_left_title"] = "{0} 已退出游戏",
            ["netplay_host_left_sub"] = "在线对局已结束，游戏即将关闭",
            ["netplay_the_host"] = "主机",
            ["replay_searching"] = "正在查找回放…",
            ["replay_searching_sub"] = "正在联系保存它的街机",
            ["replay_1lc_end"] = "1LC 结束",
            ["replay_1lc_end_sub"] = "失去第一条命：1LC 分数到此为止。",
            ["replay_no_seek"] = "无法快进",
            ["replay_no_seek_sub"] = "此回放录制时没有检查点：只能从头看到尾。",
            ["world_scoring_updated"] = "World Scoring 已更新：本机台有 {0} 款游戏可玩",
            ["world_scoring_updated_one"] = "World Scoring 已更新：本机台有 {0} 款游戏可玩",
            ["replay_requested"] = "回放暂不可用",
            ["replay_requested_sub"] = "已向录制它的街机请求：请几分钟后再试",
            ["replay_unavailable"] = "暂时找不到回放",
            ["replay_unavailable_sub"] = "没有在线街机共享它",
            ["replay_rom_missing"] = "本机没有该游戏",
            ["replay_rom_missing_sub"] = "播放此回放需要本机有该游戏",
            ["replay_core_missing"] = "本机没有该模拟器",
            ["replay_core_missing_sub"] = "此回放需要录制时使用的模拟器",
        },
        ["ko"] = new()
        {
            ["start_title"] = "START를 눌러 시작하세요",
            ["start_sub"] = "자동으로 일시정지됩니다 - 출발 준비",
            ["hold_title"] = "손을 떼 주세요!",
            ["hold_sub"] = "일시정지 - 곧 시작합니다, 카운트다운을 기다려 주세요",
            ["reached_title"] = "🏁 목표 달성!",
            ["reached_sub"] = "기록이 저장되었습니다 - 순위표를 확인하세요!",
            ["end_title"] = "🏁 챌린지 종료!",
            ["end_sub"] = "순위는 매장 화면에 - 참여해 주셔서 감사합니다!",
            ["countdown"] = "시작까지…",
            ["go"] = "GO!",
            ["ready"] = "준비하세요!",
            ["launching"] = "게임을 실행하는 중…",
            ["scan"] = "📱 스캔해서 참여 - 점수는 당신의 이름으로",
            ["open_to_all"] = "누구나 참여 가능",
            ["scoring_certifiable"] = "인증 가능한 플레이",
            ["scoring_for_ranking"] = "랭킹에 반영됩니다",
            ["scoring_forced"] = "인증 설정이 적용되었습니다",
            ["scoring_factory_reset"] = "게임 설정을 공장 기본값으로 되돌렸습니다: {0}",
            ["scoring_not_certifiable"] = "인증할 수 없는 플레이",
            ["scoring_frontend_off"] = "{0}: 이 게임의 RetroBat 옵션에서 끄세요",
            ["scoring_danger_rewind"] = "되감기(Rewind)",
            ["scoring_danger_runahead"] = "런어헤드",
            ["scoring_danger_autosave"] = "자동 상태 저장",
            ["scoring_emulator_pending"] = "아직 인식되지 않은 에뮬레이터",
            ["scoring_emulator_pending_sub"] = "인식되는 즉시 점수가 보관되고 랭킹에 반영됩니다",
            ["scoring_settings_pending"] = "설정 확인 대기 중",
            ["scoring_settings_pending_sub"] = "설정이 인식되는 즉시 점수가 보관되고 랭킹에 반영됩니다",
            ["scoring_nothing_measured"] = "점수가 측정되지 않습니다",
            ["scoring_module_missing"] = "이 기기에는 측정 모듈이 없습니다",
            ["scoring_module_idle"] = "측정 모듈이 어떤 에뮬레이터에도 연결되어 있지 않습니다",
            ["scoring_core_blind"] = "코어 “{0}”은(는) 메모리를 공개하지 않습니다",
            ["scoring_none_measured"] = "측정된 점수가 없습니다",
            ["scoring_none_measured_sub"] = "인증 가능으로 안내된 플레이에서 아무것도 전달되지 않았습니다",
            ["scoring_kept_offline"] = "점수 {0}을(를) 기기에 저장했습니다. NelfePlay가 복구되면 전송됩니다",
            ["scoring_deferred_sent"] = "NelfePlay가 복구되었습니다. 기기에 저장된 {0}개의 플레이를 전송했습니다",
            ["scoring_deferred_sent_rank"] = "NelfePlay가 복구되었습니다. {0}개 전송, 최고 순위 #{1}",
            ["scoring_offline"] = "NelfePlay에 연결할 수 없습니다",
            ["scoring_offline_sub"] = "평소처럼 플레이하세요. 복구되면 점수가 전송됩니다",
            ["scoring_offline_certifiable_sub"] = "인증 가능한 플레이입니다. NelfePlay가 복구되면 점수가 전송됩니다",
            ["reason_profile_content_mismatch"] = "ROM이 인식되지 않습니다",
            ["reason_profile_mem_mismatch"] = "메모리 정의가 인식되지 않습니다",
            ["reason_game_mode_unmeasured"] = "게임 모드를 측정하지 못했습니다: APIExpose를 업데이트하세요",
            ["reason_profile_api_outdated"] = "이 순위에 비해 APIExpose 버전이 너무 오래되었습니다: APIExpose를 업데이트하세요",
            ["reason_game_mode_mismatch"] = "게임 모드가 이 순위표와 다릅니다",
            ["reason_game_difficulty_unmeasured"] = "난이도를 측정하지 못했습니다",
            ["reason_game_difficulty_not_allowed"] = "이 순위표에서 허용되지 않는 난이도입니다",
            ["reason_game_multiplayer"] = "여러 명이 플레이: 1인 순위 제외",
            ["reason_profile_listener_unauthorized"] = "측정 모듈이 승인되지 않았습니다(wrapper 또는 MAME 플러그인)",
            ["reason_profile_not_open"] = "랭킹이 닫혀 있습니다",
            ["reason_profile_nvram_mismatch"] = "게임 내부 설정이 공장 초기값과 다릅니다",
            ["reason_profile_bios_mismatch"] = "BIOS가 인식되지 않습니다",
            ["reason_profile_mismatch"] = "게임 또는 규칙이 일치하지 않습니다",
            ["reason_runtime_module_unauthorized"] = "승인되지 않은 소프트웨어",
            ["replay_uncertain"] = "재생이 불안정할 수 있음",
            ["replay_downloading"] = "리플레이 다운로드 중…",
            ["replay_download_percent"] = "다운로드 중 {0}%",
            ["replay_download_eta"] = "{0}초 남음",
            ["replay_download_size"] = "{0} MB / {1}",
            ["replay_this_core"] = "이 코어",
            ["replay_core_other"] = "이 기록은 다른 버전의 {0}(으)로 만들어졌습니다. 재생이 끝나기 전에 멈출 수 있습니다.",
            ["replay_core_other_local"] = "이 기록은 다른 버전의 {0}(으)로 만들어졌습니다. 이 기기는 {1}입니다. 재생이 끝나기 전에 멈출 수 있습니다.",
            ["replay_rom_other"] = "이 기기에는 기록 당시와 같은 파일이 없습니다. {0}(으)로 재생합니다. 게임이 다르면(지역, 리비전) 리플레이가 어긋날 수 있습니다.",
            ["replay_rom_other_crc"] = "이 기기에는 기록 당시와 같은 파일(체크섬 {1})이 없습니다. {0}(으)로 재생합니다. 게임이 다르면(지역, 리비전) 리플레이가 어긋날 수 있습니다.",
            ["scoring_continue_title"] = "이어하기: 인증 점수는 {0}(으)로 유지됩니다",
            ["scoring_continue_sub"] = "게임은 계속되지만 이후 점수는 순위에 반영되지 않습니다",
            ["netplay_player_title"] = "{0}님의 게임에 플레이어로 참가합니다",
            ["netplay_player_sub"] = "컨트롤러로 상대 게임의 내 자리를 조작합니다",
            ["netplay_spectator_title"] = "{0}님의 게임을 관전합니다",
            ["netplay_spectator_sub"] = "버튼으로 반응을 보냅니다",
            ["netplay_this_live"] = "이 라이브",
            ["netplay_host_left_title"] = "{0} 님이 게임을 나갔습니다",
            ["netplay_host_left_sub"] = "온라인 게임이 끝났습니다. 게임을 종료합니다",
            ["netplay_the_host"] = "호스트",
            ["replay_searching"] = "리플레이를 찾는 중…",
            ["replay_searching_sub"] = "보관 중인 기기에 요청하는 중",
            ["replay_1lc_end"] = "1LC 종료",
            ["replay_1lc_end_sub"] = "첫 번째 목숨을 잃었습니다. 1LC 점수는 여기까지입니다.",
            ["replay_no_seek"] = "빨리 감기 불가",
            ["replay_no_seek_sub"] = "이 리플레이는 체크포인트 없이 녹화되어 처음부터 끝까지 재생됩니다.",
            ["world_scoring_updated"] = "World Scoring 업데이트: 이 기기에서 {0}개 게임을 즐길 수 있습니다",
            ["world_scoring_updated_one"] = "World Scoring 업데이트: 이 기기에서 {0}개 게임을 즐길 수 있습니다",
            ["replay_requested"] = "리플레이를 아직 볼 수 없습니다",
            ["replay_requested_sub"] = "녹화한 기기에 요청했습니다. 몇 분 후 다시 시도하세요",
            ["replay_unavailable"] = "지금은 리플레이를 찾을 수 없습니다",
            ["replay_unavailable_sub"] = "공유 중인 온라인 기기가 없습니다",
            ["replay_rom_missing"] = "이 기기에 게임이 없습니다",
            ["replay_rom_missing_sub"] = "이 리플레이를 보려면 게임이 필요합니다",
            ["replay_core_missing"] = "이 기기에 에뮬레이터가 없습니다",
            ["replay_core_missing_sub"] = "이 리플레이에는 기록 당시의 에뮬레이터가 필요합니다",
        },
    };
}
